-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE ELECTRONICS_SUPPLY_CHAIN;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.FACTORIES (
  FACTORY_ID VARCHAR(20) NOT NULL, FACTORY_NAME VARCHAR(200), PROVINCE VARCHAR(50), FACTORY_TYPE VARCHAR(30), CAPACITY FLOAT, EMPLOYEES INT, CERTIFICATION VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTION_LINES (
  LINE_ID VARCHAR(20) NOT NULL, FACTORY_ID VARCHAR(20), LINE_NAME VARCHAR(100), PRODUCT_TYPE VARCHAR(50), CAPACITY_UNITS_HR INT, STATUS VARCHAR(20), LAST_MAINTENANCE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WORK_ORDERS (
  WO_ID VARCHAR(30) NOT NULL, LINE_ID VARCHAR(20), ORDER_DATE TIMESTAMP, PRODUCT VARCHAR(100), TARGET_QTY INT, ACTUAL_QTY INT, DEFECT_QTY INT, RUNTIME_HOURS FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.QUALITY_TESTS (
  TEST_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), TEST_DATE TIMESTAMP, TEST_TYPE VARCHAR(50), PARAMETER VARCHAR(50), VALUE FLOAT, THRESHOLD FLOAT, RESULT VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
