-- Generated from generator/demo_specs/aws-vietnam-electronics-supply-chain.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-electronics-supply-chain
-- This is the schema that is actually deployed for VIETNAM_ELECTRONICS_SUPPLY_CHAIN.

-- Alerts fire on the bottom tail of On-Time Delivery
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ON_TIME_DELIVERY) AS T
  FROM RAW.COMPONENT_SHIPMENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ON_TIME_DELIVERY <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY,
  ROUND(AVG(f.KPI_COMPONENT_SHORTAGE), 2) AS AVG_COMPONENT_SHORTAGE,
  ROUND(AVG(f.KPI_LEAD_TIME_AVG), 2) AS AVG_LEAD_TIME,
  ROUND(AVG(f.KPI_BUFFER_STOCK), 2) AS AVG_BUFFER_STOCK,
  ROUND(AVG(f.KPI_ALTERNATIVES_QUALIFIED), 2) AS AVG_ALTERNATIVES_QUALIFIED
FROM RAW.COMPONENT_SHIPMENTS f
JOIN RAW.SUPPLIERS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY,
  ROUND(AVG(f.KPI_COMPONENT_SHORTAGE), 2) AS AVG_COMPONENT_SHORTAGE,
  ROUND(AVG(f.KPI_LEAD_TIME_AVG), 2) AS AVG_LEAD_TIME,
  ROUND(AVG(f.KPI_BUFFER_STOCK), 2) AS AVG_BUFFER_STOCK,
  ROUND(AVG(f.KPI_ALTERNATIVES_QUALIFIED), 2) AS AVG_ALTERNATIVES_QUALIFIED
FROM RAW.COMPONENT_SHIPMENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ON_TIME_DELIVERY) AS KPI_ON_TIME_DELIVERY, AVG(KPI_COMPONENT_SHORTAGE) AS KPI_COMPONENT_SHORTAGE, AVG(KPI_LEAD_TIME_AVG) AS KPI_LEAD_TIME_AVG, AVG(KPI_BUFFER_STOCK) AS KPI_BUFFER_STOCK, AVG(KPI_ALTERNATIVES_QUALIFIED) AS KPI_ALTERNATIVES_QUALIFIED FROM RAW.COMPONENT_SHIPMENTS),
     en AS (SELECT SUM(KPI_ACTIVE_SUPPLIERS) AS KPI_ACTIVE_SUPPLIERS, SUM(KPI_SINGLE_SOURCE_RISK) AS KPI_SINGLE_SOURCE_RISK FROM RAW.SUPPLIERS)
  SELECT 1 AS SORT_ORDER, 'On-Time Delivery' AS TITLE, KPI_ON_TIME_DELIVERY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ON_TIME_DELIVERY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Component Shortage' AS TITLE, KPI_COMPONENT_SHORTAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_COMPONENT_SHORTAGE)) AS DECIMAL(38,0))) || ' ' || 'SKUs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Lead Time (Avg)' AS TITLE, KPI_LEAD_TIME_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_LEAD_TIME_AVG), 1) AS DECIMAL(38,1))) || ' ' || 'weeks' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Suppliers' AS TITLE, KPI_ACTIVE_SUPPLIERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_SUPPLIERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Single-Source Risk' AS TITLE, KPI_SINGLE_SOURCE_RISK AS VALUE_NUM, '₫' || TO_VARCHAR(CAST(ROUND(((KPI_SINGLE_SOURCE_RISK) / 1000000000)) AS DECIMAL(38,0))) || 'B' || ' ' || 'exposure' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Buffer Stock' AS TITLE, KPI_BUFFER_STOCK AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BUFFER_STOCK)) AS DECIMAL(38,0))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Alternatives Qualified' AS TITLE, KPI_ALTERNATIVES_QUALIFIED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ALTERNATIVES_QUALIFIED)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
