-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Electronics Supply Chain Visibility
-- ============================================================================
USE DATABASE ELECTRONICS_SUPPLY_CHAIN;
USE SCHEMA ML;

-- ML.FORECAST: LEAD_TIME_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.LEAD_TIME_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.LEAD_TIME_ANALYTICS'),
  SERIES_COLNAME => 'SUPPLIER_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.LEAD_TIME_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.LEAD_TIME_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: SUPPLY_DISRUPTION_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SUPPLY_DISRUPTION_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.LEAD_TIME_ANALYTICS'),
  SERIES_COLNAME => 'SUPPLIER_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SUPPLY_DISRUPTION_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.SUPPLY_DISRUPTION_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.LEAD_TIME_ANALYTICS'), SERIES_COLNAME => 'SUPPLIER_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

