-- ============================================================================
-- 99_RESET.SQL — Reset Electronics Supply Chain Visibility to clean demo state
-- ============================================================================
USE DATABASE ELECTRONICS_SUPPLY_CHAIN;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.SUPPLIER_RISK_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.DELIVERY_COMPLIANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.LEAD_TIME_ANALYTICS REFRESH;
ALTER DYNAMIC TABLE CURATED.SUPPLY_GRAPH REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ELECTRONICS_SUPPLY_CHAIN.RAW.SUPPLIERS → 200
-- SELECT COUNT(*) FROM ELECTRONICS_SUPPLY_CHAIN.RAW.BOM_ITEMS → 5000
-- SELECT COUNT(*) FROM ELECTRONICS_SUPPLY_CHAIN.RAW.PURCHASE_ORDERS → 30000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_AI RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
